/*
 * Flink Client API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.api;

import com.nextbreakpoint.flinkclient1_15.ApiClient;
import com.nextbreakpoint.flinkclient1_15.ApiException;
import com.nextbreakpoint.flinkclient1_15.Configuration;
import com.nextbreakpoint.flinkclient1_15.Pair;
import com.nextbreakpoint.flinkclient1_15.ProgressRequestBody;
import com.nextbreakpoint.flinkclient1_15.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient apiClient;

    private static final String HEADER_CONTENT_TYPE = "Content-Type";

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    // Example method using the constant
    public void someMethod() throws ApiException {
        // ...
        Map<String, String> headerParams = new HashMap<>();
        headerParams.put(HEADER_CONTENT_TYPE, "application/json");
        // ...
    }

    // ... other methods using HEADER_CONTENT_TYPE instead of "Content-Type"
}
