# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us James Wrong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- $serviceType := .Values.service.type }}

## see:https://kubernetes.io/zh/docs/concepts/services-networking/service/#discovering-services
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "app.chart" . }}
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}

spec:
  type: {{ $serviceType }}
  {{- if eq $serviceType "LoadBalancer" }}
  {{- if not (empty .Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if not (empty .Values.service.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if not (empty .Values.service.externalIPs) }}
  ## see:https://kubernetes.io/zh/docs/concepts/services-networking/service/#external-ips
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- end }}

  ports:
  {{- range $name, $expose := .Values.service.exposes }}
  - name: {{ $expose.protocol7 | lower }}-{{ $name }}
    port: {{ $expose.port | default 8080 }}
    protocol: {{ $expose.protocol4 | default "TCP" }}
    ## Notice: If the TCP protocol is monitored here but the application layer is the HTTP protocol,
    ## the port name must start with 'http-', otherwise the istio-proxy startupProbe/livenessProbe will fail???
    targetPort: {{ $expose.protocol7 | lower }}-{{ $name }}
    {{- if and (or (eq $serviceType "NodePort") (eq $serviceType "LoadBalancer")) (not (empty $expose.nodePort)) }}
    nodePort: {{ $expose.nodePort }}
    {{- else if eq $serviceType "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}

  selector:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/release: {{ .Release.Name }}