# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment Swagger configuration. ####
#

## see:https://springdoc.org/#springdoc-openapi-core-properties
## see:https://github1s.com/springdoc/springdoc-openapi-demos/blob/HEAD/springdoc-openapi-spring-boot-2-webmvc/src/main/resources/application.yml#L1-L21
## see:org.springdoc.core.SpringDocConfigProperties
## see:org.springdoc.core.GroupedOpenApi#getPackagesToScan()
## see:org.springdoc.webmvc.api.OpenApiResource#openapiJson()
## see:org.springdoc.api.AbstractOpenApiResource#getOpenApi()
## see:org.springdoc.api.AbstractOpenApiResource#isPackageToScan()
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs ## Default by '/v3/api-docs'
    packagesToScan: 'com.wl4g.rengine'
    groups:
      enabled: true ## Default by false
  disable-i18n: false
  show-actuator: false ## Default by false
  use-management-port: false ## Default by false
  group-configs:
    - group: apiserver-docs
      pathsToMatch: /v1/**
      packagesToScan: com.wl4g.rengine.apiserver
  swagger-ui:
    enabled: true ## Default by true
    path: /swagger-ui.html
    #configUrl: ${springdoc.api-docs.path}/swagger-config ## Default by '/v3/api-docs/swagger-config'
    #layout: BaseLayout
    displayRequestDuration: true ## Default by false
    disableSwaggerDefaultUrl: true ## Default by false
    displayOperationId: false ## Default by false
    defaultModelsExpandDepth: 1 ## Default by 1
    defaultModelExpandDepth: 1 ## Default by 1
    #defaultModelRendering:
    useRootPath: true ## Default by false
    supportedSubmitMethods: ['get','put','post','delete','options','head','patch','trace']
    showCommonExtensions: true ## Default by false
    showExtensions: false ## Default by false
    deepLinking: true ## Default by false
    operationsSorter: method
    #tagsSorter:
    oauth2RedirectUrl: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: ${IAM_CLIENT_ID:rengine}
      clientSecret: ${IAM_CLIENT_SECRET:FvLNs0sbwF3sN4BbyjZ5GBwN819QFCmF}
      realm: ${IAM_REALM:master}
      appName: ${spring.application.name}
      #additionalQueryStringParams:
      useBasicAuthenticationWithAccessCodeGrant: false ## Default by false
    csrf:
      enabled: true ## Default by false
      use-local-storage: true ## Default by false
      use-session-stroage: true ## Default by false
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN
    syntaxHighlight:
      activated: true
      theme: agate ## Default by 'agate', Options: agate|arta|monokai|nord|obsidian|tomorrow-night
    urlsPrimaryName: ${springdoc.group-configs[0].group:api}
    #urls:
    #  - name: local
    #    url: http://localhost:${server.port}${server.servlet.contextPath:/}v3/api-docs
  customOASConfig:
    project:
      name: ${spring.application.name:MyApp}
      #description: "@project.description@ APIs Documention"
      description: "${spring.application.name:MyApp} APIs Documention"
      encoding: "@project.build.sourceEncoding@"
      termsOfService: "http://swagger.io/terms/"
    license:
      name: "Apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0"
    contact:
      name: James Wong
      email: jameswong1376@gmail.com
      url: https://github.com/wl4g
      extensions: {}
    replaceClassConfig: {}
    ## see:io.swagger.v3.oas.annotations.security.SecurityScheme
    securitySchemes:
      default_oauth:
        enabled: true
        ## see:io.swagger.v3.oas.annotations.enums.SecuritySchemeType
        type: OAUTH2 ## DEFAULT|HTTP|APIKEY|OAUTH2|OPENIDCONNECT
        ## see:io.swagger.v3.oas.models.security.SecurityScheme
        in: HEADER ## HEADER|COOKIE|QUERY
        flows: ## see:io.swagger.v3.oas.models.security.OAuthFlows
          #password: {}
          #implicit: {}
          #clientCredentials: {}
          authorizationCode:
            authorizationUrl: ${IAM_ENDPOINT:http://localhost:8083}/realms/${IAM_REALM:master}/protocol/openid-connect/auth
            tokenUrl: ${IAM_ENDPOINT:http://localhost:8083}/realms/${IAM_REALM:master}/protocol/openid-connect/token
            #refreshUrl:
            #extensions: {}
            scopes:
              read: read scope
              write: write scope
