# Copyright (c) 2017 ~ 2025, the original authors individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Collector Job configuration. ####
#

rengine:
  scheduler:
    zookeeper:
      #serverLists: "#{T(java.net.InetAddress).getLocalHost().getHostName()}:2181"
      serverLists: localhost:2181
      namespace: rengine
      baseSleepTimeMilliseconds: 1000
      maxSleepTimeMilliseconds: 3000
      maxRetries: 3
      sessionTimeoutMilliseconds: 0
      connectionTimeoutMilliseconds: 5
      #digest:
    tracing:
      type: RDB
      includeJobNames: []
      excludeJobNames: []
    dump:
      enabled: true
      port: 9888
    controller:
      disabled: false ## Default by false
      overwrite: true ## Default by true
      monitorExecution: true ## Default by true
      failover: false ## Default by false
      misfire: false ## Default by false
      cron: "0/5 * * * * ?"
      timeZone: GMT+08:00
      maxTimeDiffSeconds: -1
      reconcileIntervalMinutes: 0
      ## When setup true, the shardingTotalCount will be ignored, and the will be automatically allocated according to the number of cluster nodes priority.
      autoShardingTotalCount: true
      shardingTotalCount: 1
      shardingItemParameters: 0=Beijing,1=Shanghai
      jobShardingStrategyType: ""
      jobExecutorServiceHandlerType: ""
      jobErrorHandlerType: ""
      jobListenerTypes: []
      description: The job engine execution schedule controller.
    purger:
      logRetentionHour: 168 ## 7*24
      logRetentionCount: 1_000_000
    client:
      concurrency: 10
      acceptQueue: 2
    flink:
      concurrency: 5
      acceptQueue: 1
