# Copyright (c) 2017 ^ 2025, the original author James Wong individual Inc,
# All rights reserved. Contact us <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @see: https://helm.sh/zh/docs/topics/charts/
#
apiVersion: v2
name: rengine-stack
description: A Helm chart for Rengine Application Stack
icon: https://raw.githubusercontent.com/wl4g/rengine/master/shots/logo.png?token=GHSAT0AAAAAABWBQKN3QNYHECQ5LR4PCLKMYWGQIGA
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

# Onwer maintainers.
maintainers:
  - name: James Wong
    email: jameswong1376@gmail.com
    url: https://github.com/wl4g

## For best performance, these stateful storage services, which are relied upon below, usually use services
## outside the kubernetes cluster (headless endpoints) in production environments.
## Global values see to: https://github.com/wl4g-k8s/helm-doc-zh-cn/blob/master/chart_template_guide/subcharts_and_globals-zh_cn.md#全局-chart-值
## Check version matching see to: https://github.com/Masterminds/semver#tilde-range-comparisons-patch
dependencies:
  - name: "rengine-apiserver"
    condition: rengine-apiserver.enabled
    repository: "file://charts/rengine-apiserver"
    version: "~1.0.0"
  - name: "rengine-executor"
    condition: rengine-executor.enabled
    repository: "file://charts/rengine-executor"
    version: "~1.0.0"
  - name: "rengine-controller"
    condition: rengine-controller.enabled
    repository: "file://charts/rengine-controller"
    version: "~1.0.0"
  - name: "rengine-ui"
    condition: rengine-ui.enabled
    repository: "file://charts/rengine-ui"
    version: "~1.0.0"
  - name: "jaeger"
    condition: global.components.jaeger.internal.enabled
    repository: "https://jaegertracing.github.io/helm-charts"
    version: "~0.57.1"
  - name: "jaeger-operator"
    condition: global.components.jaeger.internal.enabled
    repository: "https://jaegertracing.github.io/helm-charts"
    version: "~2.33.0"
  - name: "zookeeper"
    condition: global.components.zookeeper.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "~10.0.2"
  - name: "kafka"
    condition: global.components.kafka.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "~18.0.3"
  - name: "redis"
    condition: global.components.redis.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "~17.0.x"
  #- name: "mysql"
  #  condition: global.components.mysql.internal.enabled
  #  repository: "https://charts.bitnami.com/bitnami"
  #  version: "~9.2.x"
  - name: "mongodb"
    condition: global.components.mongodb.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "~12.1.27"
  - name: "minio"
    condition: global.components.minio.internal.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "~11.7.13"
  # - name: "vault"
  #   condition: global.components.vault.disabled
  #   repository: https://helm.releases.hashicorp.com
  #   version: "~0.6.0"

