# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us James Wrong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- $appName := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- $appChart := printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- $releaseName := .Release.Name }}
{{- $releaseService := .Release.Service }}
{{- $releaseServiceName := .Release.ServiceName }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $capabilitiesKubeVersion := .Capabilities.KubeVersion.Version }}
{{- $serviceExposes := .Values.service.exposes }}

{{- if eq .Values.governance.provider "Ingress" }}
---
{{- range $name, $conf := .Values.governance.ingress }}
{{- if $conf.enabled -}}
{{- if semverCompare ">=1.19-0" $capabilitiesKubeVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $capabilitiesKubeVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $appName }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/release: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
    helm.sh/chart: {{ $appChart }}
  {{- if not (empty $conf.annotations) }}
  annotations:
    {{- toYaml $conf.annotations | nindent 4 }}
  {{- end }}

spec:
  {{- if and $conf.ingressClassName (semverCompare ">=1.18-0" $capabilitiesKubeVersion) }}
  ingressClassName: {{ $conf.ingressClassName }}
  {{- end }}

  rules:
  {{- if empty $conf.customHosts }}
  - host: {{ $appName }}.{{ $releaseNamespace }}.svc.cluster.local
    http:
      paths:
      - path: /
        {{- if (semverCompare ">=1.18-0" $capabilitiesKubeVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $capabilitiesKubeVersion }}
          service:
            name: {{ template "app.name" $ }}
            port:
              number: {{ index $serviceExposes $name "port" }}
          {{- else }}
          serviceName: {{ template "app.name" $ }}
          servicePort: {{ index $serviceExposes $name "port" }}
          {{- end }}
  {{- else }}
  {{- range $host := $conf.customHosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        {{- if (semverCompare ">=1.18-0" $capabilitiesKubeVersion) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $capabilitiesKubeVersion }}
          service:
            name: {{ template "app.name" $ }}
            port:
              number: {{ index .Values.service.exposes $name "port" }}
          {{- else }}
          serviceName: {{ template "app.name" $ }}
          servicePort: {{ index .Values.service.exposes $name "port" }}
          {{- end }}
  {{- end -}}
  {{- end -}}
  {{- if $conf.tls }}
  tls:
    {{- toYaml $conf.tls | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}

{{- end }}
