# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us James Wrong James Wong<jamewong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"
networks:
  rengine:
    external: false

services:
  # TODO
  #mysql:
  #mongodb:
  #minio:
  #redis:
  rengine:
    image: wl4g/rengine-web:latest
    container_name: rengine
    environment:
      ## Please your modify by actual.
      - RENGINE_REDIS_NODES='10.0.0.114:6379,10.0.0.114:6380,10.0.0.114:6381,10.0.0.114:7379,10.0.0.114:7380,10.0.0.114:7381'
      - RENGINE_REDIS_PASSWORD='zzx!@#$%'
    restart: always
    networks:
      - rengine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/disk1/rengine/:/mnt/disk1/rengine/
      - /mnt/disk1/log/rengine/:/mnt/disk1/log/rengine/
    ports:
      - "28001:28001"
      - "10108:10108"
