# Copyright (c) 2017 ~ 2025, the original authors individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment base configuration. ####
#

spring:
  application.name: rengine-example
  profiles:
    active: rengine
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #mvc:
  #  pathmatch:
  #    matching-strategy: /**/swagger-ui/**

server:
  port: 28004
  servlet:
    contextPath: /
  tomcat:
    basedir: /tmp/${spring.application.name}
