# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment Arthas configuration. ####
#

## see:https://arthas.aliyun.com/doc/spring-boot-starter.html
## see:com.taobao.arthas:arthas-spring-boot-starter(com.alibaba.arthas.spring.ArthasProperties)
arthas:
  agent-id: renginecontrollervfu6y
  telnet-port: 3660
  http-port: 8565
  tunnel-server: ws://localhost:7777/ws
  session-timeout: 1800
  #username: admin
  #password: admin