# Copyright (c) 2017 ~ 2025, the original authors individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment base configuration. ####
#

# #### Spring boot configuration. ####
#
spring:
  application.name: rengine
  profiles:
    include: common,util,apm
    active: dev
  banner:
      location: classpath:META-INF/banner.txt
  main:
    allow-circular-references: true

# Logging configuration.
logging:
  file:
    # see:com.wl4g.infra.core.logging.logback.EnhancedLogbackConfigurer#apply
    # see:org.springframework.boot.logging.LogFile#toString
    name: ${server.tomcat.basedir}/../log/${spring.application.name}/${spring.application.name}.log
    clean-history-on-start: false # By default: false
    total-size-cap: 200GB # By default: 200GB
    max-size: 1GB # By default: 500MB
    max-history: 30 # By default: 7
  pattern:
    #console: ${logging.pattern.file.name}
    #file: '%d{yy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%4p} ${PID} [%t] [%X{_H_:X-Request-ID}] [%X{_H_:X-Request-Seq}] [%X{_C_:${spring.rengine.cookie.name}}] - %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    #dateformat: yyyy-MM-dd HH:mm:ss.SSS
    #level: '%5p'
    #rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  root: INFO
  level:
    de.codecentric.boot.admin: INFO
    org:
      springframework: INFO
        #boot.context.config: DEBUG # Print load config
      apache: INFO
    feign: DEBUG
    com:
      wl4g.rengine: DEBUG

# ### Server configuration. ###
server: ## see:org.springframework.boot.autoconfigure.web.ServerProperties
  port: 18081
  address: 0.0.0.0
  servlet:
    #contextPath: /${spring.application.name}
    ## The spring-cloud-loadbalancer-2.2.6 not support metadata.contextPath
    contextPath: /
  tomcat: # see: org.springframework.boot.autoconfigure.web.ServerProperties.Tomcat
    basedir: /tmp/${spring.application.name}
    accesslog:
      enabled: false
      directory: ${server.tomcat.basedir}/../log/${spring.application.name}/ # Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
      requestAttributesEnabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
    backgroundProcessorDelay: 1000 # default: 10s
    thread:
      # Maximum amount of worker threads. for example 4C 8G, and the empirical value of thread number is 800. The operating system 
      # has system overhead for switching and scheduling between threads, so not the more the better. The minimum number of idle working threads
      # is 10 by default. (increase it appropriately to cope with the sudden increase of visits). default: 200
      max: 50
      min-spare: 5 # Minimum amount of worker threads. default: 10
    # Maximum number of connections that the server accepts and processes at any given time. Once the limit has been reached, the
    # operating system may still accept connections based on the "acceptCount" property. default: 8192
    maxConnections: 8192
    # Maximum queue length for incoming connection requests when all possible request processing threads are in use. defualt: 100
    accept-count: 100
    # Maximum number of idle processors that will be retained in the cache and reused with a subsequent request. When set to -1 
    # the cache will be unlimited with a theoretical maximum size equal to the maximum number of connections. default: 200
    processorCache: 200
    maxHttpFormPostSize: 2MB # Maximum size of the form content in any HTTP post request.
    maxSwallowSize: 2MB # Maximum amount of request body to swallow.
    uri-encoding: UTF-8
    mbeanregistry:
      enable: true
    remoteip:
      remoteIpHeader: X-Forwarded-For
      protocolHeader: X-Forwarded-Proto
      hostHeader: X-Forwarded-Host
      portHeader: X-Forwarded-Port

