/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CheckpointDuration
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class CheckpointDuration {
    @SerializedName("sync")
    private Long sync = null;

    @SerializedName("async")
    private Long async = null;

    public CheckpointDuration sync(Long sync) {
        this.sync = sync;
        return this;
    }

    /**
     * Get sync
     * 
     * @return sync
     **/
    @Schema(description = "")
    public Long getSync() {
        return sync;
    }

    public void setSync(Long sync) {
        this.sync = sync;
    }

    public CheckpointDuration async(Long async) {
        this.async = async;
        return this;
    }

    /**
     * Get async
     * 
     * @return async
     **/
    @Schema(description = "")
    public Long getAsync() {
        return async;
    }

    public void setAsync(Long async) {
        this.async = async;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CheckpointDuration checkpointDuration = (CheckpointDuration) o;
        return Objects.equals(this.sync, checkpointDuration.sync) && Objects.equals(this.async, checkpointDuration.async);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sync, async);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CheckpointDuration {\n");

        sb.append("    sync: ").append(toIndentedString(sync)).append("\n");
        sb.append("    async: ").append(toIndentedString(async)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
