/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ClusterDataSetEntry
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class ClusterDataSetEntry {
    @SerializedName("id")
    private String id = null;

    @SerializedName("isComplete")
    private Boolean isComplete = null;

    public ClusterDataSetEntry id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ClusterDataSetEntry isComplete(Boolean isComplete) {
        this.isComplete = isComplete;
        return this;
    }

    /**
     * Get isComplete
     * 
     * @return isComplete
     **/
    @Schema(description = "")
    public Boolean isIsComplete() {
        return isComplete;
    }

    public void setIsComplete(Boolean isComplete) {
        this.isComplete = isComplete;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ClusterDataSetEntry clusterDataSetEntry = (ClusterDataSetEntry) o;
        return Objects.equals(this.id, clusterDataSetEntry.id) && Objects.equals(this.isComplete, clusterDataSetEntry.isComplete);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, isComplete);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ClusterDataSetEntry {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    isComplete: ").append(toIndentedString(isComplete)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
