/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CompletedCheckpointStatistics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class CompletedCheckpointStatistics extends CheckpointStatistics {
    @SerializedName("external_path")
    private String externalPath = null;

    @SerializedName("discarded")
    private Boolean discarded = null;

    public CompletedCheckpointStatistics externalPath(String externalPath) {
        this.externalPath = externalPath;
        return this;
    }

    /**
     * Get externalPath
     * 
     * @return externalPath
     **/
    @Schema(description = "")
    public String getExternalPath() {
        return externalPath;
    }

    public void setExternalPath(String externalPath) {
        this.externalPath = externalPath;
    }

    public CompletedCheckpointStatistics discarded(Boolean discarded) {
        this.discarded = discarded;
        return this;
    }

    /**
     * Get discarded
     * 
     * @return discarded
     **/
    @Schema(description = "")
    public Boolean isDiscarded() {
        return discarded;
    }

    public void setDiscarded(Boolean discarded) {
        this.discarded = discarded;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompletedCheckpointStatistics completedCheckpointStatistics = (CompletedCheckpointStatistics) o;
        return Objects.equals(this.externalPath, completedCheckpointStatistics.externalPath)
                && Objects.equals(this.discarded, completedCheckpointStatistics.discarded) && super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(externalPath, discarded, super.hashCode());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompletedCheckpointStatistics {\n");
        sb.append("    ").append(toIndentedString(super.toString())).append("\n");
        sb.append("    externalPath: ").append(toIndentedString(externalPath)).append("\n");
        sb.append("    discarded: ").append(toIndentedString(discarded)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
