/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ExternalizedCheckpointInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class ExternalizedCheckpointInfo {
    @SerializedName("enabled")
    private Boolean enabled = null;

    @SerializedName("delete_on_cancellation")
    private Boolean deleteOnCancellation = null;

    public ExternalizedCheckpointInfo enabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Get enabled
     * 
     * @return enabled
     **/
    @Schema(description = "")
    public Boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public ExternalizedCheckpointInfo deleteOnCancellation(Boolean deleteOnCancellation) {
        this.deleteOnCancellation = deleteOnCancellation;
        return this;
    }

    /**
     * Get deleteOnCancellation
     * 
     * @return deleteOnCancellation
     **/
    @Schema(description = "")
    public Boolean isDeleteOnCancellation() {
        return deleteOnCancellation;
    }

    public void setDeleteOnCancellation(Boolean deleteOnCancellation) {
        this.deleteOnCancellation = deleteOnCancellation;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExternalizedCheckpointInfo externalizedCheckpointInfo = (ExternalizedCheckpointInfo) o;
        return Objects.equals(this.enabled, externalizedCheckpointInfo.enabled)
                && Objects.equals(this.deleteOnCancellation, externalizedCheckpointInfo.deleteOnCancellation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(enabled, deleteOnCancellation);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExternalizedCheckpointInfo {\n");

        sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
        sb.append("    deleteOnCancellation: ").append(toIndentedString(deleteOnCancellation)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
