/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * FailedCheckpointStatistics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class FailedCheckpointStatistics extends CheckpointStatistics {
    @SerializedName("failure_timestamp")
    private Long failureTimestamp = null;

    @SerializedName("failure_message")
    private String failureMessage = null;

    public FailedCheckpointStatistics failureTimestamp(Long failureTimestamp) {
        this.failureTimestamp = failureTimestamp;
        return this;
    }

    /**
     * Get failureTimestamp
     * 
     * @return failureTimestamp
     **/
    @Schema(description = "")
    public Long getFailureTimestamp() {
        return failureTimestamp;
    }

    public void setFailureTimestamp(Long failureTimestamp) {
        this.failureTimestamp = failureTimestamp;
    }

    public FailedCheckpointStatistics failureMessage(String failureMessage) {
        this.failureMessage = failureMessage;
        return this;
    }

    /**
     * Get failureMessage
     * 
     * @return failureMessage
     **/
    @Schema(description = "")
    public String getFailureMessage() {
        return failureMessage;
    }

    public void setFailureMessage(String failureMessage) {
        this.failureMessage = failureMessage;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FailedCheckpointStatistics failedCheckpointStatistics = (FailedCheckpointStatistics) o;
        return Objects.equals(this.failureTimestamp, failedCheckpointStatistics.failureTimestamp)
                && Objects.equals(this.failureMessage, failedCheckpointStatistics.failureMessage) && super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(failureTimestamp, failureMessage, super.hashCode());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FailedCheckpointStatistics {\n");
        sb.append("    ").append(toIndentedString(super.toString())).append("\n");
        sb.append("    failureTimestamp: ").append(toIndentedString(failureTimestamp)).append("\n");
        sb.append("    failureMessage: ").append(toIndentedString(failureMessage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
