/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Features
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class Features {
    @SerializedName("web-submit")
    private Boolean webSubmit = null;

    @SerializedName("web-cancel")
    private Boolean webCancel = null;

    public Features webSubmit(Boolean webSubmit) {
        this.webSubmit = webSubmit;
        return this;
    }

    /**
     * Get webSubmit
     * 
     * @return webSubmit
     **/
    @Schema(description = "")
    public Boolean isWebSubmit() {
        return webSubmit;
    }

    public void setWebSubmit(Boolean webSubmit) {
        this.webSubmit = webSubmit;
    }

    public Features webCancel(Boolean webCancel) {
        this.webCancel = webCancel;
        return this;
    }

    /**
     * Get webCancel
     * 
     * @return webCancel
     **/
    @Schema(description = "")
    public Boolean isWebCancel() {
        return webCancel;
    }

    public void setWebCancel(Boolean webCancel) {
        this.webCancel = webCancel;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Features features = (Features) o;
        return Objects.equals(this.webSubmit, features.webSubmit) && Objects.equals(this.webCancel, features.webCancel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(webSubmit, webCancel);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Features {\n");

        sb.append("    webSubmit: ").append(toIndentedString(webSubmit)).append("\n");
        sb.append("    webCancel: ").append(toIndentedString(webCancel)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
