/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JarPlanRequestBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JarPlanRequestBody {
    @SerializedName("entryClass")
    private String entryClass = null;

    @SerializedName("programArgs")
    private String programArgs = null;

    @SerializedName("programArgsList")
    private List<String> programArgsList = null;

    @SerializedName("parallelism")
    private Integer parallelism = null;

    @SerializedName("jobId")
    private String jobId = null;

    public JarPlanRequestBody entryClass(String entryClass) {
        this.entryClass = entryClass;
        return this;
    }

    /**
     * Get entryClass
     * 
     * @return entryClass
     **/
    @Schema(description = "")
    public String getEntryClass() {
        return entryClass;
    }

    public void setEntryClass(String entryClass) {
        this.entryClass = entryClass;
    }

    public JarPlanRequestBody programArgs(String programArgs) {
        this.programArgs = programArgs;
        return this;
    }

    /**
     * Get programArgs
     * 
     * @return programArgs
     **/
    @Schema(description = "")
    public String getProgramArgs() {
        return programArgs;
    }

    public void setProgramArgs(String programArgs) {
        this.programArgs = programArgs;
    }

    public JarPlanRequestBody programArgsList(List<String> programArgsList) {
        this.programArgsList = programArgsList;
        return this;
    }

    public JarPlanRequestBody addProgramArgsListItem(String programArgsListItem) {
        if (this.programArgsList == null) {
            this.programArgsList = new ArrayList<String>();
        }
        this.programArgsList.add(programArgsListItem);
        return this;
    }

    /**
     * Get programArgsList
     * 
     * @return programArgsList
     **/
    @Schema(description = "")
    public List<String> getProgramArgsList() {
        return programArgsList;
    }

    public void setProgramArgsList(List<String> programArgsList) {
        this.programArgsList = programArgsList;
    }

    public JarPlanRequestBody parallelism(Integer parallelism) {
        this.parallelism = parallelism;
        return this;
    }

    /**
     * Get parallelism
     * 
     * @return parallelism
     **/
    @Schema(description = "")
    public Integer getParallelism() {
        return parallelism;
    }

    public void setParallelism(Integer parallelism) {
        this.parallelism = parallelism;
    }

    public JarPlanRequestBody jobId(String jobId) {
        this.jobId = jobId;
        return this;
    }

    /**
     * Get jobId
     * 
     * @return jobId
     **/
    @Schema(description = "")
    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JarPlanRequestBody jarPlanRequestBody = (JarPlanRequestBody) o;
        return Objects.equals(this.entryClass, jarPlanRequestBody.entryClass)
                && Objects.equals(this.programArgs, jarPlanRequestBody.programArgs)
                && Objects.equals(this.programArgsList, jarPlanRequestBody.programArgsList)
                && Objects.equals(this.parallelism, jarPlanRequestBody.parallelism)
                && Objects.equals(this.jobId, jarPlanRequestBody.jobId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(entryClass, programArgs, programArgsList, parallelism, jobId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JarPlanRequestBody {\n");

        sb.append("    entryClass: ").append(toIndentedString(entryClass)).append("\n");
        sb.append("    programArgs: ").append(toIndentedString(programArgs)).append("\n");
        sb.append("    programArgsList: ").append(toIndentedString(programArgsList)).append("\n");
        sb.append("    parallelism: ").append(toIndentedString(parallelism)).append("\n");
        sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
