/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JobConfigInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JobConfigInfo {
    @SerializedName("jobId")
    private String jobId = null;

    @SerializedName("jobName")
    private String jobName = null;

    @SerializedName("executionConfigInfo")
    private ExecutionConfigInfo executionConfigInfo = null;

    public JobConfigInfo jobId(String jobId) {
        this.jobId = jobId;
        return this;
    }

    /**
     * Get jobId
     * 
     * @return jobId
     **/
    @Schema(description = "")
    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public JobConfigInfo jobName(String jobName) {
        this.jobName = jobName;
        return this;
    }

    /**
     * Get jobName
     * 
     * @return jobName
     **/
    @Schema(description = "")
    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public JobConfigInfo executionConfigInfo(ExecutionConfigInfo executionConfigInfo) {
        this.executionConfigInfo = executionConfigInfo;
        return this;
    }

    /**
     * Get executionConfigInfo
     * 
     * @return executionConfigInfo
     **/
    @Schema(description = "")
    public ExecutionConfigInfo getExecutionConfigInfo() {
        return executionConfigInfo;
    }

    public void setExecutionConfigInfo(ExecutionConfigInfo executionConfigInfo) {
        this.executionConfigInfo = executionConfigInfo;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobConfigInfo jobConfigInfo = (JobConfigInfo) o;
        return Objects.equals(this.jobId, jobConfigInfo.jobId) && Objects.equals(this.jobName, jobConfigInfo.jobName)
                && Objects.equals(this.executionConfigInfo, jobConfigInfo.executionConfigInfo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jobId, jobName, executionConfigInfo);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobConfigInfo {\n");

        sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
        sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
        sb.append("    executionConfigInfo: ").append(toIndentedString(executionConfigInfo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
