/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * StopWithSavepointRequestBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class StopWithSavepointRequestBody {
    @SerializedName("targetDirectory")
    private String targetDirectory = null;

    @SerializedName("drain")
    private Boolean drain = null;

    @SerializedName("triggerId")
    private String triggerId = null;

    public StopWithSavepointRequestBody targetDirectory(String targetDirectory) {
        this.targetDirectory = targetDirectory;
        return this;
    }

    /**
     * Get targetDirectory
     * 
     * @return targetDirectory
     **/
    @Schema(description = "")
    public String getTargetDirectory() {
        return targetDirectory;
    }

    public void setTargetDirectory(String targetDirectory) {
        this.targetDirectory = targetDirectory;
    }

    public StopWithSavepointRequestBody drain(Boolean drain) {
        this.drain = drain;
        return this;
    }

    /**
     * Get drain
     * 
     * @return drain
     **/
    @Schema(description = "")
    public Boolean isDrain() {
        return drain;
    }

    public void setDrain(Boolean drain) {
        this.drain = drain;
    }

    public StopWithSavepointRequestBody triggerId(String triggerId) {
        this.triggerId = triggerId;
        return this;
    }

    /**
     * Get triggerId
     * 
     * @return triggerId
     **/
    @Schema(description = "")
    public String getTriggerId() {
        return triggerId;
    }

    public void setTriggerId(String triggerId) {
        this.triggerId = triggerId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StopWithSavepointRequestBody stopWithSavepointRequestBody = (StopWithSavepointRequestBody) o;
        return Objects.equals(this.targetDirectory, stopWithSavepointRequestBody.targetDirectory)
                && Objects.equals(this.drain, stopWithSavepointRequestBody.drain)
                && Objects.equals(this.triggerId, stopWithSavepointRequestBody.triggerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(targetDirectory, drain, triggerId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class StopWithSavepointRequestBody {\n");

        sb.append("    targetDirectory: ").append(toIndentedString(targetDirectory)).append("\n");
        sb.append("    drain: ").append(toIndentedString(drain)).append("\n");
        sb.append("    triggerId: ").append(toIndentedString(triggerId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
