/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.io.IOException;
import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SubtaskBackPressureInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class SubtaskBackPressureInfo {
    @SerializedName("subtask")
    private Integer subtask = null;

    /**
     * Gets or Sets backpressureLevel
     */
    @JsonAdapter(BackpressureLevelEnum.Adapter.class)
    public enum BackpressureLevelEnum {
        OK("ok"), LOW("low"), HIGH("high");

        private String value;

        BackpressureLevelEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static BackpressureLevelEnum fromValue(String text) {
            for (BackpressureLevelEnum b : BackpressureLevelEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<BackpressureLevelEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final BackpressureLevelEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public BackpressureLevelEnum read(final JsonReader jsonReader) throws IOException {
                Object value = jsonReader.nextString();
                return BackpressureLevelEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("backpressureLevel")
    private BackpressureLevelEnum backpressureLevel = null;

    @SerializedName("ratio")
    private Double ratio = null;

    @SerializedName("idleRatio")
    private Double idleRatio = null;

    @SerializedName("busyRatio")
    private Double busyRatio = null;

    public SubtaskBackPressureInfo subtask(Integer subtask) {
        this.subtask = subtask;
        return this;
    }

    /**
     * Get subtask
     * 
     * @return subtask
     **/
    @Schema(description = "")
    public Integer getSubtask() {
        return subtask;
    }

    public void setSubtask(Integer subtask) {
        this.subtask = subtask;
    }

    public SubtaskBackPressureInfo backpressureLevel(BackpressureLevelEnum backpressureLevel) {
        this.backpressureLevel = backpressureLevel;
        return this;
    }

    /**
     * Get backpressureLevel
     * 
     * @return backpressureLevel
     **/
    @Schema(description = "")
    public BackpressureLevelEnum getBackpressureLevel() {
        return backpressureLevel;
    }

    public void setBackpressureLevel(BackpressureLevelEnum backpressureLevel) {
        this.backpressureLevel = backpressureLevel;
    }

    public SubtaskBackPressureInfo ratio(Double ratio) {
        this.ratio = ratio;
        return this;
    }

    /**
     * Get ratio
     * 
     * @return ratio
     **/
    @Schema(description = "")
    public Double getRatio() {
        return ratio;
    }

    public void setRatio(Double ratio) {
        this.ratio = ratio;
    }

    public SubtaskBackPressureInfo idleRatio(Double idleRatio) {
        this.idleRatio = idleRatio;
        return this;
    }

    /**
     * Get idleRatio
     * 
     * @return idleRatio
     **/
    @Schema(description = "")
    public Double getIdleRatio() {
        return idleRatio;
    }

    public void setIdleRatio(Double idleRatio) {
        this.idleRatio = idleRatio;
    }

    public SubtaskBackPressureInfo busyRatio(Double busyRatio) {
        this.busyRatio = busyRatio;
        return this;
    }

    /**
     * Get busyRatio
     * 
     * @return busyRatio
     **/
    @Schema(description = "")
    public Double getBusyRatio() {
        return busyRatio;
    }

    public void setBusyRatio(Double busyRatio) {
        this.busyRatio = busyRatio;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubtaskBackPressureInfo subtaskBackPressureInfo = (SubtaskBackPressureInfo) o;
        return Objects.equals(this.subtask, subtaskBackPressureInfo.subtask)
                && Objects.equals(this.backpressureLevel, subtaskBackPressureInfo.backpressureLevel)
                && Objects.equals(this.ratio, subtaskBackPressureInfo.ratio)
                && Objects.equals(this.idleRatio, subtaskBackPressureInfo.idleRatio)
                && Objects.equals(this.busyRatio, subtaskBackPressureInfo.busyRatio);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subtask, backpressureLevel, ratio, idleRatio, busyRatio);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubtaskBackPressureInfo {\n");

        sb.append("    subtask: ").append(toIndentedString(subtask)).append("\n");
        sb.append("    backpressureLevel: ").append(toIndentedString(backpressureLevel)).append("\n");
        sb.append("    ratio: ").append(toIndentedString(ratio)).append("\n");
        sb.append("    idleRatio: ").append(toIndentedString(idleRatio)).append("\n");
        sb.append("    busyRatio: ").append(toIndentedString(busyRatio)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
