/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SubtasksAllAccumulatorsInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class SubtasksAllAccumulatorsInfo {
    @SerializedName("id")
    private String id = null;

    @SerializedName("parallelism")
    private Integer parallelism = null;

    @SerializedName("subtasks")
    private List<SubtaskAccumulatorsInfo> subtasks = null;

    public SubtasksAllAccumulatorsInfo id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SubtasksAllAccumulatorsInfo parallelism(Integer parallelism) {
        this.parallelism = parallelism;
        return this;
    }

    /**
     * Get parallelism
     * 
     * @return parallelism
     **/
    @Schema(description = "")
    public Integer getParallelism() {
        return parallelism;
    }

    public void setParallelism(Integer parallelism) {
        this.parallelism = parallelism;
    }

    public SubtasksAllAccumulatorsInfo subtasks(List<SubtaskAccumulatorsInfo> subtasks) {
        this.subtasks = subtasks;
        return this;
    }

    public SubtasksAllAccumulatorsInfo addSubtasksItem(SubtaskAccumulatorsInfo subtasksItem) {
        if (this.subtasks == null) {
            this.subtasks = new ArrayList<SubtaskAccumulatorsInfo>();
        }
        this.subtasks.add(subtasksItem);
        return this;
    }

    /**
     * Get subtasks
     * 
     * @return subtasks
     **/
    @Schema(description = "")
    public List<SubtaskAccumulatorsInfo> getSubtasks() {
        return subtasks;
    }

    public void setSubtasks(List<SubtaskAccumulatorsInfo> subtasks) {
        this.subtasks = subtasks;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubtasksAllAccumulatorsInfo subtasksAllAccumulatorsInfo = (SubtasksAllAccumulatorsInfo) o;
        return Objects.equals(this.id, subtasksAllAccumulatorsInfo.id)
                && Objects.equals(this.parallelism, subtasksAllAccumulatorsInfo.parallelism)
                && Objects.equals(this.subtasks, subtasksAllAccumulatorsInfo.subtasks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, parallelism, subtasks);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubtasksAllAccumulatorsInfo {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    parallelism: ").append(toIndentedString(parallelism)).append("\n");
        sb.append("    subtasks: ").append(toIndentedString(subtasks)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
