/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SubtaskCheckpointStatistics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")

public class SubtaskCheckpointStatistics {
    @SerializedName("index")
    private Integer index = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("className")
    private String className = null;

    public SubtaskCheckpointStatistics() {
        this.className = this.getClass().getSimpleName();
    }

    public SubtaskCheckpointStatistics index(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Get index
     * 
     * @return index
     **/
    @Schema(description = "")
    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public SubtaskCheckpointStatistics status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * 
     * @return status
     **/
    @Schema(description = "")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public SubtaskCheckpointStatistics className(String className) {
        this.className = className;
        return this;
    }

    /**
     * Get className
     * 
     * @return className
     **/
    @Schema(required = true, description = "")
    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubtaskCheckpointStatistics subtaskCheckpointStatistics = (SubtaskCheckpointStatistics) o;
        return Objects.equals(this.index, subtaskCheckpointStatistics.index)
                && Objects.equals(this.status, subtaskCheckpointStatistics.status)
                && Objects.equals(this.className, subtaskCheckpointStatistics.className);
    }

    @Override
    public int hashCode() {
        return Objects.hash(index, status, className);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubtaskCheckpointStatistics {\n");

        sb.append("    index: ").append(toIndentedString(index)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    className: ").append(toIndentedString(className)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
