/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Summary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class Summary {
    @SerializedName("state_size")
    private StatsSummaryDto stateSize = null;

    @SerializedName("end_to_end_duration")
    private StatsSummaryDto endToEndDuration = null;

    @SerializedName("checkpoint_duration")
    private CheckpointDuration checkpointDuration = null;

    @SerializedName("alignment")
    private CheckpointAlignment alignment = null;

    @SerializedName("start_delay")
    private StatsSummaryDto startDelay = null;

    public Summary stateSize(StatsSummaryDto stateSize) {
        this.stateSize = stateSize;
        return this;
    }

    /**
     * Get stateSize
     * 
     * @return stateSize
     **/
    @Schema(description = "")
    public StatsSummaryDto getStateSize() {
        return stateSize;
    }

    public void setStateSize(StatsSummaryDto stateSize) {
        this.stateSize = stateSize;
    }

    public Summary endToEndDuration(StatsSummaryDto endToEndDuration) {
        this.endToEndDuration = endToEndDuration;
        return this;
    }

    /**
     * Get endToEndDuration
     * 
     * @return endToEndDuration
     **/
    @Schema(description = "")
    public StatsSummaryDto getEndToEndDuration() {
        return endToEndDuration;
    }

    public void setEndToEndDuration(StatsSummaryDto endToEndDuration) {
        this.endToEndDuration = endToEndDuration;
    }

    public Summary checkpointDuration(CheckpointDuration checkpointDuration) {
        this.checkpointDuration = checkpointDuration;
        return this;
    }

    /**
     * Get checkpointDuration
     * 
     * @return checkpointDuration
     **/
    @Schema(description = "")
    public CheckpointDuration getCheckpointDuration() {
        return checkpointDuration;
    }

    public void setCheckpointDuration(CheckpointDuration checkpointDuration) {
        this.checkpointDuration = checkpointDuration;
    }

    public Summary alignment(CheckpointAlignment alignment) {
        this.alignment = alignment;
        return this;
    }

    /**
     * Get alignment
     * 
     * @return alignment
     **/
    @Schema(description = "")
    public CheckpointAlignment getAlignment() {
        return alignment;
    }

    public void setAlignment(CheckpointAlignment alignment) {
        this.alignment = alignment;
    }

    public Summary startDelay(StatsSummaryDto startDelay) {
        this.startDelay = startDelay;
        return this;
    }

    /**
     * Get startDelay
     * 
     * @return startDelay
     **/
    @Schema(description = "")
    public StatsSummaryDto getStartDelay() {
        return startDelay;
    }

    public void setStartDelay(StatsSummaryDto startDelay) {
        this.startDelay = startDelay;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Summary summary = (Summary) o;
        return Objects.equals(this.stateSize, summary.stateSize)
                && Objects.equals(this.endToEndDuration, summary.endToEndDuration)
                && Objects.equals(this.checkpointDuration, summary.checkpointDuration)
                && Objects.equals(this.alignment, summary.alignment) && Objects.equals(this.startDelay, summary.startDelay);
    }

    @Override
    public int hashCode() {
        return Objects.hash(stateSize, endToEndDuration, checkpointDuration, alignment, startDelay);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Summary {\n");

        sb.append("    stateSize: ").append(toIndentedString(stateSize)).append("\n");
        sb.append("    endToEndDuration: ").append(toIndentedString(endToEndDuration)).append("\n");
        sb.append("    checkpointDuration: ").append(toIndentedString(checkpointDuration)).append("\n");
        sb.append("    alignment: ").append(toIndentedString(alignment)).append("\n");
        sb.append("    startDelay: ").append(toIndentedString(startDelay)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
