/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ThreadDumpInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class ThreadDumpInfo {
    @SerializedName("threadInfos")
    private List<ThreadInfo> threadInfos = null;

    public ThreadDumpInfo threadInfos(List<ThreadInfo> threadInfos) {
        this.threadInfos = threadInfos;
        return this;
    }

    public ThreadDumpInfo addThreadInfosItem(ThreadInfo threadInfosItem) {
        if (this.threadInfos == null) {
            this.threadInfos = new ArrayList<ThreadInfo>();
        }
        this.threadInfos.add(threadInfosItem);
        return this;
    }

    /**
     * Get threadInfos
     * 
     * @return threadInfos
     **/
    @Schema(description = "")
    public List<ThreadInfo> getThreadInfos() {
        return threadInfos;
    }

    public void setThreadInfos(List<ThreadInfo> threadInfos) {
        this.threadInfos = threadInfos;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ThreadDumpInfo threadDumpInfo = (ThreadDumpInfo) o;
        return Objects.equals(this.threadInfos, threadDumpInfo.threadInfos);
    }

    @Override
    public int hashCode() {
        return Objects.hash(threadInfos);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ThreadDumpInfo {\n");

        sb.append("    threadInfos: ").append(toIndentedString(threadInfos)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
