/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * AsynchronousOperationResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class AsynchronousOperationResult {
    @SerializedName("status")
    private QueueStatus status = null;

    @SerializedName("operation")
    private OneOfAsynchronousOperationResultOperation operation = null;

    public AsynchronousOperationResult status(QueueStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * 
     * @return status
     **/
    @Schema(description = "")
    public QueueStatus getStatus() {
        return status;
    }

    public void setStatus(QueueStatus status) {
        this.status = status;
    }

    public AsynchronousOperationResult operation(OneOfAsynchronousOperationResultOperation operation) {
        this.operation = operation;
        return this;
    }

    /**
     * Get operation
     * 
     * @return operation
     **/
    @Schema(description = "")
    public OneOfAsynchronousOperationResultOperation getOperation() {
        return operation;
    }

    public void setOperation(OneOfAsynchronousOperationResultOperation operation) {
        this.operation = operation;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AsynchronousOperationResult asynchronousOperationResult = (AsynchronousOperationResult) o;
        return Objects.equals(this.status, asynchronousOperationResult.status)
                && Objects.equals(this.operation, asynchronousOperationResult.operation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, operation);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AsynchronousOperationResult {\n");

        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
