/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CheckpointStatistics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")

public class CheckpointStatistics {
    @SerializedName("id")
    private Long id = null;

    /**
     * Gets or Sets status
     */
    @JsonAdapter(StatusEnum.Adapter.class)
    public enum StatusEnum {
        IN_PROGRESS("IN_PROGRESS"), COMPLETED("COMPLETED"), FAILED("FAILED");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static StatusEnum fromValue(String text) {
            for (StatusEnum b : StatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<StatusEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public StatusEnum read(final JsonReader jsonReader) throws IOException {
                Object value = jsonReader.nextString();
                return StatusEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("status")
    private StatusEnum status = null;

    @SerializedName("is_savepoint")
    private Boolean isSavepoint = null;

    @SerializedName("trigger_timestamp")
    private Long triggerTimestamp = null;

    @SerializedName("latest_ack_timestamp")
    private Long latestAckTimestamp = null;

    @SerializedName("state_size")
    private Long stateSize = null;

    @SerializedName("end_to_end_duration")
    private Long endToEndDuration = null;

    @SerializedName("alignment_buffered")
    private Long alignmentBuffered = null;

    @SerializedName("processed_data")
    private Long processedData = null;

    @SerializedName("persisted_data")
    private Long persistedData = null;

    @SerializedName("num_subtasks")
    private Integer numSubtasks = null;

    @SerializedName("num_acknowledged_subtasks")
    private Integer numAcknowledgedSubtasks = null;

    /**
     * Gets or Sets checkpointType
     */
    @JsonAdapter(CheckpointTypeEnum.Adapter.class)
    public enum CheckpointTypeEnum {
        CHECKPOINT("CHECKPOINT"), SAVEPOINT("SAVEPOINT"), SYNC_SAVEPOINT("SYNC_SAVEPOINT");

        private String value;

        CheckpointTypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static CheckpointTypeEnum fromValue(String text) {
            for (CheckpointTypeEnum b : CheckpointTypeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<CheckpointTypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final CheckpointTypeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public CheckpointTypeEnum read(final JsonReader jsonReader) throws IOException {
                Object value = jsonReader.nextString();
                return CheckpointTypeEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("checkpoint_type")
    private CheckpointTypeEnum checkpointType = null;

    @SerializedName("tasks")
    private Map<String, TaskCheckpointStatistics> tasks = null;

    @SerializedName("className")
    private String className = null;

    public CheckpointStatistics() {
        this.className = this.getClass().getSimpleName();
    }

    public CheckpointStatistics id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CheckpointStatistics status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * 
     * @return status
     **/
    @Schema(description = "")
    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public CheckpointStatistics isSavepoint(Boolean isSavepoint) {
        this.isSavepoint = isSavepoint;
        return this;
    }

    /**
     * Get isSavepoint
     * 
     * @return isSavepoint
     **/
    @Schema(description = "")
    public Boolean isIsSavepoint() {
        return isSavepoint;
    }

    public void setIsSavepoint(Boolean isSavepoint) {
        this.isSavepoint = isSavepoint;
    }

    public CheckpointStatistics triggerTimestamp(Long triggerTimestamp) {
        this.triggerTimestamp = triggerTimestamp;
        return this;
    }

    /**
     * Get triggerTimestamp
     * 
     * @return triggerTimestamp
     **/
    @Schema(description = "")
    public Long getTriggerTimestamp() {
        return triggerTimestamp;
    }

    public void setTriggerTimestamp(Long triggerTimestamp) {
        this.triggerTimestamp = triggerTimestamp;
    }

    public CheckpointStatistics latestAckTimestamp(Long latestAckTimestamp) {
        this.latestAckTimestamp = latestAckTimestamp;
        return this;
    }

    /**
     * Get latestAckTimestamp
     * 
     * @return latestAckTimestamp
     **/
    @Schema(description = "")
    public Long getLatestAckTimestamp() {
        return latestAckTimestamp;
    }

    public void setLatestAckTimestamp(Long latestAckTimestamp) {
        this.latestAckTimestamp = latestAckTimestamp;
    }

    public CheckpointStatistics stateSize(Long stateSize) {
        this.stateSize = stateSize;
        return this;
    }

    /**
     * Get stateSize
     * 
     * @return stateSize
     **/
    @Schema(description = "")
    public Long getStateSize() {
        return stateSize;
    }

    public void setStateSize(Long stateSize) {
        this.stateSize = stateSize;
    }

    public CheckpointStatistics endToEndDuration(Long endToEndDuration) {
        this.endToEndDuration = endToEndDuration;
        return this;
    }

    /**
     * Get endToEndDuration
     * 
     * @return endToEndDuration
     **/
    @Schema(description = "")
    public Long getEndToEndDuration() {
        return endToEndDuration;
    }

    public void setEndToEndDuration(Long endToEndDuration) {
        this.endToEndDuration = endToEndDuration;
    }

    public CheckpointStatistics alignmentBuffered(Long alignmentBuffered) {
        this.alignmentBuffered = alignmentBuffered;
        return this;
    }

    /**
     * Get alignmentBuffered
     * 
     * @return alignmentBuffered
     **/
    @Schema(description = "")
    public Long getAlignmentBuffered() {
        return alignmentBuffered;
    }

    public void setAlignmentBuffered(Long alignmentBuffered) {
        this.alignmentBuffered = alignmentBuffered;
    }

    public CheckpointStatistics processedData(Long processedData) {
        this.processedData = processedData;
        return this;
    }

    /**
     * Get processedData
     * 
     * @return processedData
     **/
    @Schema(description = "")
    public Long getProcessedData() {
        return processedData;
    }

    public void setProcessedData(Long processedData) {
        this.processedData = processedData;
    }

    public CheckpointStatistics persistedData(Long persistedData) {
        this.persistedData = persistedData;
        return this;
    }

    /**
     * Get persistedData
     * 
     * @return persistedData
     **/
    @Schema(description = "")
    public Long getPersistedData() {
        return persistedData;
    }

    public void setPersistedData(Long persistedData) {
        this.persistedData = persistedData;
    }

    public CheckpointStatistics numSubtasks(Integer numSubtasks) {
        this.numSubtasks = numSubtasks;
        return this;
    }

    /**
     * Get numSubtasks
     * 
     * @return numSubtasks
     **/
    @Schema(description = "")
    public Integer getNumSubtasks() {
        return numSubtasks;
    }

    public void setNumSubtasks(Integer numSubtasks) {
        this.numSubtasks = numSubtasks;
    }

    public CheckpointStatistics numAcknowledgedSubtasks(Integer numAcknowledgedSubtasks) {
        this.numAcknowledgedSubtasks = numAcknowledgedSubtasks;
        return this;
    }

    /**
     * Get numAcknowledgedSubtasks
     * 
     * @return numAcknowledgedSubtasks
     **/
    @Schema(description = "")
    public Integer getNumAcknowledgedSubtasks() {
        return numAcknowledgedSubtasks;
    }

    public void setNumAcknowledgedSubtasks(Integer numAcknowledgedSubtasks) {
        this.numAcknowledgedSubtasks = numAcknowledgedSubtasks;
    }

    public CheckpointStatistics checkpointType(CheckpointTypeEnum checkpointType) {
        this.checkpointType = checkpointType;
        return this;
    }

    /**
     * Get checkpointType
     * 
     * @return checkpointType
     **/
    @Schema(description = "")
    public CheckpointTypeEnum getCheckpointType() {
        return checkpointType;
    }

    public void setCheckpointType(CheckpointTypeEnum checkpointType) {
        this.checkpointType = checkpointType;
    }

    public CheckpointStatistics tasks(Map<String, TaskCheckpointStatistics> tasks) {
        this.tasks = tasks;
        return this;
    }

    public CheckpointStatistics putTasksItem(String key, TaskCheckpointStatistics tasksItem) {
        if (this.tasks == null) {
            this.tasks = new HashMap<String, TaskCheckpointStatistics>();
        }
        this.tasks.put(key, tasksItem);
        return this;
    }

    /**
     * Get tasks
     * 
     * @return tasks
     **/
    @Schema(description = "")
    public Map<String, TaskCheckpointStatistics> getTasks() {
        return tasks;
    }

    public void setTasks(Map<String, TaskCheckpointStatistics> tasks) {
        this.tasks = tasks;
    }

    public CheckpointStatistics className(String className) {
        this.className = className;
        return this;
    }

    /**
     * Get className
     * 
     * @return className
     **/
    @Schema(required = true, description = "")
    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CheckpointStatistics checkpointStatistics = (CheckpointStatistics) o;
        return Objects.equals(this.id, checkpointStatistics.id) && Objects.equals(this.status, checkpointStatistics.status)
                && Objects.equals(this.isSavepoint, checkpointStatistics.isSavepoint)
                && Objects.equals(this.triggerTimestamp, checkpointStatistics.triggerTimestamp)
                && Objects.equals(this.latestAckTimestamp, checkpointStatistics.latestAckTimestamp)
                && Objects.equals(this.stateSize, checkpointStatistics.stateSize)
                && Objects.equals(this.endToEndDuration, checkpointStatistics.endToEndDuration)
                && Objects.equals(this.alignmentBuffered, checkpointStatistics.alignmentBuffered)
                && Objects.equals(this.processedData, checkpointStatistics.processedData)
                && Objects.equals(this.persistedData, checkpointStatistics.persistedData)
                && Objects.equals(this.numSubtasks, checkpointStatistics.numSubtasks)
                && Objects.equals(this.numAcknowledgedSubtasks, checkpointStatistics.numAcknowledgedSubtasks)
                && Objects.equals(this.checkpointType, checkpointStatistics.checkpointType)
                && Objects.equals(this.tasks, checkpointStatistics.tasks)
                && Objects.equals(this.className, checkpointStatistics.className);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, status, isSavepoint, triggerTimestamp, latestAckTimestamp, stateSize, endToEndDuration,
                alignmentBuffered, processedData, persistedData, numSubtasks, numAcknowledgedSubtasks, checkpointType, tasks,
                className);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CheckpointStatistics {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    isSavepoint: ").append(toIndentedString(isSavepoint)).append("\n");
        sb.append("    triggerTimestamp: ").append(toIndentedString(triggerTimestamp)).append("\n");
        sb.append("    latestAckTimestamp: ").append(toIndentedString(latestAckTimestamp)).append("\n");
        sb.append("    stateSize: ").append(toIndentedString(stateSize)).append("\n");
        sb.append("    endToEndDuration: ").append(toIndentedString(endToEndDuration)).append("\n");
        sb.append("    alignmentBuffered: ").append(toIndentedString(alignmentBuffered)).append("\n");
        sb.append("    processedData: ").append(toIndentedString(processedData)).append("\n");
        sb.append("    persistedData: ").append(toIndentedString(persistedData)).append("\n");
        sb.append("    numSubtasks: ").append(toIndentedString(numSubtasks)).append("\n");
        sb.append("    numAcknowledgedSubtasks: ").append(toIndentedString(numAcknowledgedSubtasks)).append("\n");
        sb.append("    checkpointType: ").append(toIndentedString(checkpointType)).append("\n");
        sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
        sb.append("    className: ").append(toIndentedString(className)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
