/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * GarbageCollectorInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class GarbageCollectorInfo {
    @SerializedName("name")
    private String name = null;

    @SerializedName("count")
    private Long count = null;

    @SerializedName("time")
    private Long time = null;

    public GarbageCollectorInfo name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public GarbageCollectorInfo count(Long count) {
        this.count = count;
        return this;
    }

    /**
     * Get count
     * 
     * @return count
     **/
    @Schema(description = "")
    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public GarbageCollectorInfo time(Long time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     * 
     * @return time
     **/
    @Schema(description = "")
    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GarbageCollectorInfo garbageCollectorInfo = (GarbageCollectorInfo) o;
        return Objects.equals(this.name, garbageCollectorInfo.name) && Objects.equals(this.count, garbageCollectorInfo.count)
                && Objects.equals(this.time, garbageCollectorInfo.time);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, count, time);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GarbageCollectorInfo {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("    time: ").append(toIndentedString(time)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
