/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JobExceptionHistory
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JobExceptionHistory {
    @SerializedName("entries")
    private List<RootExceptionInfo> entries = null;

    @SerializedName("truncated")
    private Boolean truncated = null;

    public JobExceptionHistory entries(List<RootExceptionInfo> entries) {
        this.entries = entries;
        return this;
    }

    public JobExceptionHistory addEntriesItem(RootExceptionInfo entriesItem) {
        if (this.entries == null) {
            this.entries = new ArrayList<RootExceptionInfo>();
        }
        this.entries.add(entriesItem);
        return this;
    }

    /**
     * Get entries
     * 
     * @return entries
     **/
    @Schema(description = "")
    public List<RootExceptionInfo> getEntries() {
        return entries;
    }

    public void setEntries(List<RootExceptionInfo> entries) {
        this.entries = entries;
    }

    public JobExceptionHistory truncated(Boolean truncated) {
        this.truncated = truncated;
        return this;
    }

    /**
     * Get truncated
     * 
     * @return truncated
     **/
    @Schema(description = "")
    public Boolean isTruncated() {
        return truncated;
    }

    public void setTruncated(Boolean truncated) {
        this.truncated = truncated;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobExceptionHistory jobExceptionHistory = (JobExceptionHistory) o;
        return Objects.equals(this.entries, jobExceptionHistory.entries)
                && Objects.equals(this.truncated, jobExceptionHistory.truncated);
    }

    @Override
    public int hashCode() {
        return Objects.hash(entries, truncated);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobExceptionHistory {\n");

        sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
        sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
