/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JobExecutionResultResponseBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JobExecutionResultResponseBody {
    @SerializedName("status")
    private QueueStatus status = null;

    @SerializedName("job-execution-result")
    private JobResult jobExecutionResult = null;

    public JobExecutionResultResponseBody status(QueueStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * 
     * @return status
     **/
    @Schema(required = true, description = "")
    public QueueStatus getStatus() {
        return status;
    }

    public void setStatus(QueueStatus status) {
        this.status = status;
    }

    public JobExecutionResultResponseBody jobExecutionResult(JobResult jobExecutionResult) {
        this.jobExecutionResult = jobExecutionResult;
        return this;
    }

    /**
     * Get jobExecutionResult
     * 
     * @return jobExecutionResult
     **/
    @Schema(description = "")
    public JobResult getJobExecutionResult() {
        return jobExecutionResult;
    }

    public void setJobExecutionResult(JobResult jobExecutionResult) {
        this.jobExecutionResult = jobExecutionResult;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobExecutionResultResponseBody jobExecutionResultResponseBody = (JobExecutionResultResponseBody) o;
        return Objects.equals(this.status, jobExecutionResultResponseBody.status)
                && Objects.equals(this.jobExecutionResult, jobExecutionResultResponseBody.jobExecutionResult);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, jobExecutionResult);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobExecutionResultResponseBody {\n");

        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    jobExecutionResult: ").append(toIndentedString(jobExecutionResult)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
