/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JobIdsWithStatusOverview
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JobIdsWithStatusOverview {
    @SerializedName("jobs")
    private List<JobIdWithStatus> jobs = null;

    public JobIdsWithStatusOverview jobs(List<JobIdWithStatus> jobs) {
        this.jobs = jobs;
        return this;
    }

    public JobIdsWithStatusOverview addJobsItem(JobIdWithStatus jobsItem) {
        if (this.jobs == null) {
            this.jobs = new ArrayList<JobIdWithStatus>();
        }
        this.jobs.add(jobsItem);
        return this;
    }

    /**
     * Get jobs
     * 
     * @return jobs
     **/
    @Schema(description = "")
    public List<JobIdWithStatus> getJobs() {
        return jobs;
    }

    public void setJobs(List<JobIdWithStatus> jobs) {
        this.jobs = jobs;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobIdsWithStatusOverview jobIdsWithStatusOverview = (JobIdsWithStatusOverview) o;
        return Objects.equals(this.jobs, jobIdsWithStatusOverview.jobs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jobs);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobIdsWithStatusOverview {\n");

        sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
