/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JobsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JobsBody {
    @SerializedName("request")
    private JobSubmitRequestBody request = null;

    @SerializedName("filename")
    private List<File> filename = null;

    public JobsBody request(JobSubmitRequestBody request) {
        this.request = request;
        return this;
    }

    /**
     * Get request
     * 
     * @return request
     **/
    @Schema(description = "")
    public JobSubmitRequestBody getRequest() {
        return request;
    }

    public void setRequest(JobSubmitRequestBody request) {
        this.request = request;
    }

    public JobsBody filename(List<File> filename) {
        this.filename = filename;
        return this;
    }

    public JobsBody addFilenameItem(File filenameItem) {
        if (this.filename == null) {
            this.filename = new ArrayList<File>();
        }
        this.filename.add(filenameItem);
        return this;
    }

    /**
     * Get filename
     * 
     * @return filename
     **/
    @Schema(description = "")
    public List<File> getFilename() {
        return filename;
    }

    public void setFilename(List<File> filename) {
        this.filename = filename;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobsBody jobsBody = (JobsBody) o;
        return Objects.equals(this.request, jobsBody.request) && Objects.equals(this.filename, jobsBody.filename);
    }

    @Override
    public int hashCode() {
        return Objects.hash(request, filename);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobsBody {\n");

        sb.append("    request: ").append(toIndentedString(request)).append("\n");
        sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
