/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JobVertexTaskManagersInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class JobVertexTaskManagersInfo {
    @SerializedName("id")
    private String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("now")
    private Long now = null;

    @SerializedName("taskmanagers")
    private List<TaskManagersInfo> taskmanagers = null;

    public JobVertexTaskManagersInfo id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public JobVertexTaskManagersInfo name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public JobVertexTaskManagersInfo now(Long now) {
        this.now = now;
        return this;
    }

    /**
     * Get now
     * 
     * @return now
     **/
    @Schema(description = "")
    public Long getNow() {
        return now;
    }

    public void setNow(Long now) {
        this.now = now;
    }

    public JobVertexTaskManagersInfo taskmanagers(List<TaskManagersInfo> taskmanagers) {
        this.taskmanagers = taskmanagers;
        return this;
    }

    public JobVertexTaskManagersInfo addTaskmanagersItem(TaskManagersInfo taskmanagersItem) {
        if (this.taskmanagers == null) {
            this.taskmanagers = new ArrayList<TaskManagersInfo>();
        }
        this.taskmanagers.add(taskmanagersItem);
        return this;
    }

    /**
     * Get taskmanagers
     * 
     * @return taskmanagers
     **/
    @Schema(description = "")
    public List<TaskManagersInfo> getTaskmanagers() {
        return taskmanagers;
    }

    public void setTaskmanagers(List<TaskManagersInfo> taskmanagers) {
        this.taskmanagers = taskmanagers;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobVertexTaskManagersInfo jobVertexTaskManagersInfo = (JobVertexTaskManagersInfo) o;
        return Objects.equals(this.id, jobVertexTaskManagersInfo.id) && Objects.equals(this.name, jobVertexTaskManagersInfo.name)
                && Objects.equals(this.now, jobVertexTaskManagersInfo.now)
                && Objects.equals(this.taskmanagers, jobVertexTaskManagersInfo.taskmanagers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, now, taskmanagers);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobVertexTaskManagersInfo {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    now: ").append(toIndentedString(now)).append("\n");
        sb.append("    taskmanagers: ").append(toIndentedString(taskmanagers)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
