/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.io.File;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SerializedThrowable
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class SerializedThrowable {
    @SerializedName("serialized-throwable")
    private File serializedThrowable = null;

    public SerializedThrowable serializedThrowable(File serializedThrowable) {
        this.serializedThrowable = serializedThrowable;
        return this;
    }

    /**
     * Get serializedThrowable
     * 
     * @return serializedThrowable
     **/
    @Schema(description = "")
    public File getSerializedThrowable() {
        return serializedThrowable;
    }

    public void setSerializedThrowable(File serializedThrowable) {
        this.serializedThrowable = serializedThrowable;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SerializedThrowable serializedThrowable = (SerializedThrowable) o;
        return Objects.equals(this.serializedThrowable, serializedThrowable.serializedThrowable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(Objects.hashCode(serializedThrowable));
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SerializedThrowable {\n");

        sb.append("    serializedThrowable: ").append(toIndentedString(serializedThrowable)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
