/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SerializedValueOptionalFailureObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class SerializedValueOptionalFailureObject {
    @SerializedName("byteArray")
    private List<byte[]> byteArray = null;

    public SerializedValueOptionalFailureObject byteArray(List<byte[]> byteArray) {
        this.byteArray = byteArray;
        return this;
    }

    public SerializedValueOptionalFailureObject addByteArrayItem(byte[] byteArrayItem) {
        if (this.byteArray == null) {
            this.byteArray = new ArrayList<byte[]>();
        }
        this.byteArray.add(byteArrayItem);
        return this;
    }

    /**
     * Get byteArray
     * 
     * @return byteArray
     **/
    @Schema(description = "")
    public List<byte[]> getByteArray() {
        return byteArray;
    }

    public void setByteArray(List<byte[]> byteArray) {
        this.byteArray = byteArray;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SerializedValueOptionalFailureObject serializedValueOptionalFailureObject = (SerializedValueOptionalFailureObject) o;
        return Objects.equals(this.byteArray, serializedValueOptionalFailureObject.byteArray);
    }

    @Override
    public int hashCode() {
        return Objects.hash(byteArray);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SerializedValueOptionalFailureObject {\n");

        sb.append("    byteArray: ").append(toIndentedString(byteArray)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
