/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SubtasksTimesInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class SubtasksTimesInfo {
    @SerializedName("id")
    private String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("now")
    private Long now = null;

    @SerializedName("subtasks")
    private List<SubtaskTimeInfo> subtasks = null;

    public SubtasksTimesInfo id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SubtasksTimesInfo name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SubtasksTimesInfo now(Long now) {
        this.now = now;
        return this;
    }

    /**
     * Get now
     * 
     * @return now
     **/
    @Schema(description = "")
    public Long getNow() {
        return now;
    }

    public void setNow(Long now) {
        this.now = now;
    }

    public SubtasksTimesInfo subtasks(List<SubtaskTimeInfo> subtasks) {
        this.subtasks = subtasks;
        return this;
    }

    public SubtasksTimesInfo addSubtasksItem(SubtaskTimeInfo subtasksItem) {
        if (this.subtasks == null) {
            this.subtasks = new ArrayList<SubtaskTimeInfo>();
        }
        this.subtasks.add(subtasksItem);
        return this;
    }

    /**
     * Get subtasks
     * 
     * @return subtasks
     **/
    @Schema(description = "")
    public List<SubtaskTimeInfo> getSubtasks() {
        return subtasks;
    }

    public void setSubtasks(List<SubtaskTimeInfo> subtasks) {
        this.subtasks = subtasks;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubtasksTimesInfo subtasksTimesInfo = (SubtasksTimesInfo) o;
        return Objects.equals(this.id, subtasksTimesInfo.id) && Objects.equals(this.name, subtasksTimesInfo.name)
                && Objects.equals(this.now, subtasksTimesInfo.now) && Objects.equals(this.subtasks, subtasksTimesInfo.subtasks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, now, subtasks);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubtasksTimesInfo {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    now: ").append(toIndentedString(now)).append("\n");
        sb.append("    subtasks: ").append(toIndentedString(subtasks)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
