/*
 * Flink JobManager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1/1.15-SNAPSHOT
 * Contact: user@flink.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.nextbreakpoint.flinkclient1_15.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * TaskManagersInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-02T23:14:46.617621+08:00[Asia/Shanghai]")
public class TaskManagersInfo {
    @SerializedName("taskmanagers")
    private List<TaskManagerInfo> taskmanagers = null;

    public TaskManagersInfo taskmanagers(List<TaskManagerInfo> taskmanagers) {
        this.taskmanagers = taskmanagers;
        return this;
    }

    public TaskManagersInfo addTaskmanagersItem(TaskManagerInfo taskmanagersItem) {
        if (this.taskmanagers == null) {
            this.taskmanagers = new ArrayList<TaskManagerInfo>();
        }
        this.taskmanagers.add(taskmanagersItem);
        return this;
    }

    /**
     * Get taskmanagers
     * 
     * @return taskmanagers
     **/
    @Schema(description = "")
    public List<TaskManagerInfo> getTaskmanagers() {
        return taskmanagers;
    }

    public void setTaskmanagers(List<TaskManagerInfo> taskmanagers) {
        this.taskmanagers = taskmanagers;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TaskManagersInfo taskManagersInfo = (TaskManagersInfo) o;
        return Objects.equals(this.taskmanagers, taskManagersInfo.taskmanagers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(taskmanagers);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TaskManagersInfo {\n");

        sb.append("    taskmanagers: ").append(toIndentedString(taskmanagers)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
